album = "https://api.spotify.com/v1/albums/"
artist = "https://api.spotify.com/v1/artists/"
audiobook = "https://api.spotify.com/v1/audiobooks/"
auth = "https://accounts.spotify.com/api/token"
episode = "https://api.spotify.com/v1/episodes/"
playlist = "https://api.spotify.com/v1/playlists/"
show = "https://api.spotify.com/v1/shows/"
track = "https://api.spotify.com/v1/tracks/"

several_albums = "https://api.spotify.com/v1/albums?ids="
several_artists = "https://api.spotify.com/v1/artists?ids="
several_audiobooks = "https://api.spotify.com/v1/audiobooks?ids="
several_episodes = "https://api.spotify.com/v1/episodes?ids="
several_playlists = "https://api.spotify.com/v1/playlists?ids="
several_shows = "https://api.spotify.com/v1/shows?ids="
several_tracks = "https://api.spotify.com/v1/tracks?ids="